export type MenuCategory = {
  title: string;
  items: string[];
};

export const menuData: MenuCategory[] = [
  {
    title: "Refresh Drinks",
    items: [
      "Orange Juice",
      "Apple Juice",
      "Pineapple Juice",
      "Grape Juice",
      "Watermelon",
      "Lemonade",
      "Carrot Juice",
      "Pomegranate Juice",
      "Mint",
    ],
  },
  {
    title: "Drinks",
    items: [
      "Mineral Water",
      "Passion Fruit Mojito",
      "Blue Lemon Mojito",
      "Pineapple Mojito",
      "Nannari Mojito",
      "All Peg Bottles Cool Drinks",
    ],
  },
  {
    title: "Brunch Menu (Starter)",
    items: [
      "Soup",
      "Veg Mashroom Soup",
      "Chicken Sweet Corn Soup",
      "Chckn Lolipop",
      "Chickn Momos",
      "Prawns Stick",
      "Chicken Kathaif",
      "Chicken Nuggets",
      "Crab Nuggets",
      "Sheekh Kebab",
      "Tandoori Tikka",
    ],
  },

  {
    title: "Breads",
    items: [
      "Putt Mixed",
      "Beef Putt",
      "Carrot Putt",
      "Pineapple Putt",
      "Nool Porotta",
      "Vellepam",
      "Kann Vecha Pathiri",
      "Dosa Live",
      "Masala Dosha",
    ],
  },
  {
    title: "Fry & Grill Specials",
    items: [
      "Paneer 65",
      "Gobi Manchuryn Dry Fry",
      "Chemmmeen Broast",
      "Koonthal 65",
      "Avoli Rava Fry",
      "Kada Fry",
      "Kada Roast",
      "Kada Kondattam",
      "King Fish Tawa Fry",
      "Chicken Kabab 3 Type",
      "Spring Dry Fry",
      "Chicken Kondattam",
      "Chicken 82",
      "Chicken Kethal 65",
      "Chicken Coconut Varatti",
      "Fried Chicken",
      "Chicken Mini Broast",
      "Chatti Beef",
      "Beef Coconut Varattu",
      "Alfaham (8 Flowers)",
      "Kebab (4 Flowers)",
      "Mutton Leg Rana",
    ],
  },
  {
    title: "Normal Meals",
    items: [
      "Aviyal",
      "Sambar",
      "Pulisseri Thoran",
      "Chammandhi",
      "Fish Curry",
      "Fish Fry",
    ],
  },
  {
    title: "Sadya",
    items: ["13 Items with 1 Payasam", "17 Items with 2 Payasam"],
  },
  {
    title: "Salads",
    items: [
      "Healty Salad",
      "Pastha Salad",
      "Mexican Salad",
      "Raw Mango",
      "Raw Pineapple",
      "Mixed Fruits Salad",
      "Curd Salad",
      "Coconut Chammanthi",
    ],
  },
  {
    title: "Side Special On",
    items: [
      "Kappa Biriyani",
      "Kappa Puzhukk",
      "Chicken Noodiels",
      "Singapore Noodiels",
      "Chicken Mixed Noodiels",
    ],
  },
  {
    title: "Food Break Desert",
    items: [
      "Baklava Live",
      "Kunafa Live",
      "Stone Ice Cream Live",
      "Chocolate Combine",
      "Redvelwet Pastries",
      "Choco Wraps Pastries",
      "Caramel Pastries",
      "Francho Pastries",
      "Tender Pudding",
      "Choco Pudding",
      "Caramel Pudding",
      "Pineapple Pudding",
      "Chicku Pudding",
      "Vanilla Pudding",
      "Tender Payasam",
    ],
  },
  {
    title: "Indian Arabic Main Courses",
    items: [
      "Mutton Mandhi (Basmathi Rice)",
      "Chicken Hydrabadi Biriyani (Basmathi Rice)",
      "Sea Food Majboos (Basmathi Rice)",
      "Kashmiri Pulav (Basmathi Rice)",
      "Chicken Legon Dum Biriyani",
      "Chicken hyderabadi biryani",
      "Chicken Kabiri Rice",
      "Chicken Surbiyani",
      "Chicken Mandhi",
      "Chicken Kashmiripulav",
      "Chicken Afgani Rice",
      "Chicken Fried Rice",
      "Chicken Singapore Fried Rice",
      "Chicken Patiyala Rice",
    ],
  },
  {
    title: "Indian Arabic Main Courses (Mutton or Beef)",
    items: [
      "Malabar Dhum Biryani",
      "hyderabad biryani",
      "Kabiri Rice",
      "Surbiyan",
      "Mandhi",
      "Kashmiri Rice Afghani Pulav",
      "Patiyala Rice",
    ],
  },
  {
    title: "Sittings Available Your Budget",
    items: [
      "Normal Table Service (1 Counter 8 People)",
      "Premium Table Service (1 Counter 8 People)",
      "Normal Islamic Buffet (1 Counter 40 People)",
      "Premium Islamic Buffet (1 Counter 40 People)",
      "Classic Islamic Buffet (1 Counter 40 People)",
      "Normal Buffet Service (1 Counter 200 People)",
      "Premium Buffet Service (1 Counter 200 People)",
      "Classic Buffet Service (1 Counter 200 People)",
      "Normal Majlis (1 Counter 50 People)",
      "Premium Majlis (1 Counter 50 People)",
      "Classic Majlis (1 Counter 50 People)",
      "Stage Decore Available Your Budget",
    ],
  },
];
